### ISSUE TITLE
Về việc cài đặt tool 

### ISSUE THREAD

**Issue by ngoctrang317** [coinForRich/coin-for-rich#22]
Em chào anh. Em có thông qua Forum Machine Learning biết đến tool này của anh. Em thì đang làm đồ án tốt nghiệp liên quan đến dự báo tiền ảo nhưng e bắt đầu từ con số 0 ạ. Em cũng ko phải Computer Science and Engineering background, e chỉ mới tìm hiểu nhưng nó khá xa lạ với em. Em muốn sử dụng tool của anh cho đồ án tốt nghiệp này, em đã tải Docker rồi nhưng ko rõ để làm sao tiếp tục được nữa. Mong a hỗ trợ giúp e! 
Em xin cảm ơn anh rất nhiều.

**Comment by vincetran96** [comment]
Cám ơn bạn đã quan tâm và sử dụng app này. Mình không có thời gian để viết hướng dẫn cụ thể về Docker, nên bạn có thể tham khảo hướng dẫn sau:

[https://docs.docker.com/get-started/](https://docs.docker.com/get-started/)

Nếu bạn có thời gian và thật sự muốn biết thêm sâu hơn về Docker thì có thể xem hướng dẫn dưới đây, rất hay:

[https://docker-curriculum.com/](https://docker-curriculum.com/)

**Comment by ngoctrang317** [comment]
Cảm ơn anh đã hỗ trợ!!!!

Thân!

Vào 23:17, Th 4, 22 thg 9, 2021 Viet Anh (Vince) Tran <
***@***.***> đã viết:

**Comment by vincetran96** [comment]
Chúc bạn làm tốt đồ án tốt nghiệp!
